---
# Add configuration files
- name: pgpool.conf
  template:
    src=etc/pgpool.conf.j2
    dest=/etc/pgpool2/pgpool.conf
    owner='root'
    group='postgres'
    mode='664'
  notify: pgpool2 restart
  tags:
    - pgpool

- name: pool_hba.conf
  template:
    src=etc/pool_hba.conf
    dest=/etc/pgpool2/pool_hba.conf
    owner='root'
    group='root'
    mode='644'
  notify: pgpool2 restart
  tags:
    - pgpool
- name: pool_passwd
  template:
    src=etc/pool_passwd
    dest=/etc/pgpool2/pool_passwd
    owner='postgres'
    group='postgres'
    mode='666'
  notify: pgpool2 restart
  tags:
    - pgpool
- name: pcp.conf
  template:
    src=etc/pcp.conf
    dest=/etc/pgpool2/pcp.conf
    owner='root'
    group='root'
    mode='666'
  notify: pgpool2 restart
  tags:
    - pgpool


- name: pg_hba.conf
  template:
    src=etc/pg_hba.conf
    dest=/etc/postgresql/9.3/main/pg_hba.conf
    owner='postgres'
    group='postgres'
    mode='640'
  notify: postgresql restart
  tags:
    - pgpool
